root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/tabitha ."
  bin = "./tmp/tabitha"
  args_bin = ["serve"]
  include_ext = ["go"]
  exclude_dir = ["tmp", "static", "docs", "migrations/testdata"]
  delay = 200

[log]
  time = false

[misc]
  clean_on_exit = true
