/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SongsSlugRouteImport } from './routes/songs.$slug'
import { Route as SongsSlugPlayRouteImport } from './routes/songs.$slug.play'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsSlugRoute = SongsSlugRouteImport.update({
  id: '/songs/$slug',
  path: '/songs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsSlugPlayRoute = SongsSlugPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => SongsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/songs/$slug': typeof SongsSlugRouteWithChildren
  '/songs/$slug/play': typeof SongsSlugPlayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/songs/$slug': typeof SongsSlugRouteWithChildren
  '/songs/$slug/play': typeof SongsSlugPlayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/songs/$slug': typeof SongsSlugRouteWithChildren
  '/songs/$slug/play': typeof SongsSlugPlayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/songs/$slug' | '/songs/$slug/play'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/songs/$slug' | '/songs/$slug/play'
  id: '__root__' | '/' | '/songs/$slug' | '/songs/$slug/play'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SongsSlugRoute: typeof SongsSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/$slug': {
      id: '/songs/$slug'
      path: '/songs/$slug'
      fullPath: '/songs/$slug'
      preLoaderRoute: typeof SongsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/$slug/play': {
      id: '/songs/$slug/play'
      path: '/play'
      fullPath: '/songs/$slug/play'
      preLoaderRoute: typeof SongsSlugPlayRouteImport
      parentRoute: typeof SongsSlugRoute
    }
  }
}

interface SongsSlugRouteChildren {
  SongsSlugPlayRoute: typeof SongsSlugPlayRoute
}

const SongsSlugRouteChildren: SongsSlugRouteChildren = {
  SongsSlugPlayRoute: SongsSlugPlayRoute,
}

const SongsSlugRouteWithChildren = SongsSlugRoute._addFileChildren(
  SongsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SongsSlugRoute: SongsSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
