// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: artists_genres.sql

package db

import (
	"context"
)

const clearSongGenres = `-- name: ClearSongGenres :exec
DELETE FROM song_genres WHERE song_id = $1
`

func (q *Queries) ClearSongGenres(ctx context.Context, songID int64) error {
	_, err := q.db.Exec(ctx, clearSongGenres, songID)
	return err
}

const findOrCreateArtist = `-- name: FindOrCreateArtist :one
INSERT INTO artists (name) VALUES ($1)
ON CONFLICT (lower(name)) DO UPDATE SET name = artists.name
RETURNING id, name, created_at, updated_at
`

func (q *Queries) FindOrCreateArtist(ctx context.Context, name string) (Artist, error) {
	row := q.db.QueryRow(ctx, findOrCreateArtist, name)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findOrCreateGenre = `-- name: FindOrCreateGenre :one
INSERT INTO genres (name) VALUES ($1)
ON CONFLICT (lower(name)) DO UPDATE SET name = genres.name
RETURNING id, name, created_at, updated_at
`

func (q *Queries) FindOrCreateGenre(ctx context.Context, name string) (Genre, error) {
	row := q.db.QueryRow(ctx, findOrCreateGenre, name)
	var i Genre
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkSongGenre = `-- name: LinkSongGenre :exec
INSERT INTO song_genres (song_id, genre_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LinkSongGenreParams struct {
	SongID  int64 `json:"song_id"`
	GenreID int64 `json:"genre_id"`
}

func (q *Queries) LinkSongGenre(ctx context.Context, arg LinkSongGenreParams) error {
	_, err := q.db.Exec(ctx, linkSongGenre, arg.SongID, arg.GenreID)
	return err
}

const listGenresForSong = `-- name: ListGenresForSong :many
SELECT g.id, g.name, g.created_at, g.updated_at FROM genres g
JOIN song_genres sg ON sg.genre_id = g.id
WHERE sg.song_id = $1
ORDER BY lower(g.name)
`

func (q *Queries) ListGenresForSong(ctx context.Context, songID int64) ([]Genre, error) {
	rows, err := q.db.Query(ctx, listGenresForSong, songID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Genre
	for rows.Next() {
		var i Genre
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSongArtistID = `-- name: SetSongArtistID :exec
UPDATE songs SET artist_id = $2, updated_at = now() WHERE id = $1
`

type SetSongArtistIDParams struct {
	ID       int64  `json:"id"`
	ArtistID *int64 `json:"artist_id"`
}

func (q *Queries) SetSongArtistID(ctx context.Context, arg SetSongArtistIDParams) error {
	_, err := q.db.Exec(ctx, setSongArtistID, arg.ID, arg.ArtistID)
	return err
}
