// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type UserRole string

const (
	UserRoleUser       UserRole = "user"
	UserRoleSuperadmin UserRole = "superadmin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type GoogleOauthToken struct {
	ID                    int64              `json:"id"`
	UserID                int64              `json:"user_id"`
	EncryptedAccessToken  []byte             `json:"encrypted_access_token"`
	EncryptedRefreshToken []byte             `json:"encrypted_refresh_token"`
	Scope                 string             `json:"scope"`
	Expiry                pgtype.Timestamptz `json:"expiry"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	Token     string             `json:"token"`
	UserID    int64              `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type Song struct {
	ID               int64              `json:"id"`
	Title            string             `json:"title"`
	Artist           string             `json:"artist"`
	Genre            string             `json:"genre"`
	FilmShowAlbum    string             `json:"film_show_album"`
	Decade           string             `json:"decade"`
	BobTag           string             `json:"bob_tag"`
	Status           string             `json:"status"`
	SourceUrl        string             `json:"source_url"`
	Notes            string             `json:"notes"`
	TransposeHint    string             `json:"transpose_hint"`
	GoogleDocID      string             `json:"google_doc_id"`
	CurrentVersionID *int64             `json:"current_version_id"`
	AddedByUserID    *int64             `json:"added_by_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type TranscriptionVersion struct {
	ID        int64              `json:"id"`
	SongID    int64              `json:"song_id"`
	Kind      string             `json:"kind"`
	Source    string             `json:"source"`
	RawText   string             `json:"raw_text"`
	Content   []byte             `json:"content"`
	Key       *string            `json:"key"`
	Capo      *int32             `json:"capo"`
	IsCurrent bool               `json:"is_current"`
	CreatedBy *int64             `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        int64              `json:"id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	AvatarUrl string             `json:"avatar_url"`
	Role      UserRole           `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
