// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: songs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSongByID = `-- name: GetSongByID :one
SELECT id, title, artist, genre, film_show_album, decade, bob_tag, status, source_url, notes, transpose_hint, google_doc_id, current_version_id, added_by_user_id, created_at, updated_at, artist_id, preferred_key, doc_created_at, doc_modified_at, source_site, slug FROM songs WHERE id = $1
`

func (q *Queries) GetSongByID(ctx context.Context, id int64) (Song, error) {
	row := q.db.QueryRow(ctx, getSongByID, id)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Artist,
		&i.Genre,
		&i.FilmShowAlbum,
		&i.Decade,
		&i.BobTag,
		&i.Status,
		&i.SourceUrl,
		&i.Notes,
		&i.TransposeHint,
		&i.GoogleDocID,
		&i.CurrentVersionID,
		&i.AddedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArtistID,
		&i.PreferredKey,
		&i.DocCreatedAt,
		&i.DocModifiedAt,
		&i.SourceSite,
		&i.Slug,
	)
	return i, err
}

const getSongBySlug = `-- name: GetSongBySlug :one
SELECT id, title, artist, genre, film_show_album, decade, bob_tag, status, source_url, notes, transpose_hint, google_doc_id, current_version_id, added_by_user_id, created_at, updated_at, artist_id, preferred_key, doc_created_at, doc_modified_at, source_site, slug FROM songs WHERE slug = $1
`

func (q *Queries) GetSongBySlug(ctx context.Context, slug string) (Song, error) {
	row := q.db.QueryRow(ctx, getSongBySlug, slug)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Artist,
		&i.Genre,
		&i.FilmShowAlbum,
		&i.Decade,
		&i.BobTag,
		&i.Status,
		&i.SourceUrl,
		&i.Notes,
		&i.TransposeHint,
		&i.GoogleDocID,
		&i.CurrentVersionID,
		&i.AddedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArtistID,
		&i.PreferredKey,
		&i.DocCreatedAt,
		&i.DocModifiedAt,
		&i.SourceSite,
		&i.Slug,
	)
	return i, err
}

const getSongByTitle = `-- name: GetSongByTitle :one
SELECT id, title, artist, genre, film_show_album, decade, bob_tag, status, source_url, notes, transpose_hint, google_doc_id, current_version_id, added_by_user_id, created_at, updated_at, artist_id, preferred_key, doc_created_at, doc_modified_at, source_site, slug FROM songs WHERE lower(title) = lower($1)
`

func (q *Queries) GetSongByTitle(ctx context.Context, lower string) (Song, error) {
	row := q.db.QueryRow(ctx, getSongByTitle, lower)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Artist,
		&i.Genre,
		&i.FilmShowAlbum,
		&i.Decade,
		&i.BobTag,
		&i.Status,
		&i.SourceUrl,
		&i.Notes,
		&i.TransposeHint,
		&i.GoogleDocID,
		&i.CurrentVersionID,
		&i.AddedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArtistID,
		&i.PreferredKey,
		&i.DocCreatedAt,
		&i.DocModifiedAt,
		&i.SourceSite,
		&i.Slug,
	)
	return i, err
}

const getSongCurrentVersion = `-- name: GetSongCurrentVersion :one
SELECT songs.id, songs.title, songs.artist, songs.genre, songs.film_show_album, songs.decade, songs.bob_tag, songs.status, songs.source_url, songs.notes, songs.transpose_hint, songs.google_doc_id, songs.current_version_id, songs.added_by_user_id, songs.created_at, songs.updated_at, songs.artist_id, songs.preferred_key, songs.doc_created_at, songs.doc_modified_at, songs.source_site, songs.slug, transcription_versions.id, transcription_versions.song_id, transcription_versions.kind, transcription_versions.source, transcription_versions.raw_text, transcription_versions.content, transcription_versions.key, transcription_versions.capo, transcription_versions.is_current, transcription_versions.created_by, transcription_versions.created_at
FROM songs
JOIN transcription_versions ON transcription_versions.id = songs.current_version_id
WHERE songs.id = $1
`

type GetSongCurrentVersionRow struct {
	Song                 Song                 `json:"song"`
	TranscriptionVersion TranscriptionVersion `json:"transcription_version"`
}

func (q *Queries) GetSongCurrentVersion(ctx context.Context, id int64) (GetSongCurrentVersionRow, error) {
	row := q.db.QueryRow(ctx, getSongCurrentVersion, id)
	var i GetSongCurrentVersionRow
	err := row.Scan(
		&i.Song.ID,
		&i.Song.Title,
		&i.Song.Artist,
		&i.Song.Genre,
		&i.Song.FilmShowAlbum,
		&i.Song.Decade,
		&i.Song.BobTag,
		&i.Song.Status,
		&i.Song.SourceUrl,
		&i.Song.Notes,
		&i.Song.TransposeHint,
		&i.Song.GoogleDocID,
		&i.Song.CurrentVersionID,
		&i.Song.AddedByUserID,
		&i.Song.CreatedAt,
		&i.Song.UpdatedAt,
		&i.Song.ArtistID,
		&i.Song.PreferredKey,
		&i.Song.DocCreatedAt,
		&i.Song.DocModifiedAt,
		&i.Song.SourceSite,
		&i.Song.Slug,
		&i.TranscriptionVersion.ID,
		&i.TranscriptionVersion.SongID,
		&i.TranscriptionVersion.Kind,
		&i.TranscriptionVersion.Source,
		&i.TranscriptionVersion.RawText,
		&i.TranscriptionVersion.Content,
		&i.TranscriptionVersion.Key,
		&i.TranscriptionVersion.Capo,
		&i.TranscriptionVersion.IsCurrent,
		&i.TranscriptionVersion.CreatedBy,
		&i.TranscriptionVersion.CreatedAt,
	)
	return i, err
}

const listAllSongSlugs = `-- name: ListAllSongSlugs :many
SELECT id, slug FROM songs WHERE slug <> ''
`

type ListAllSongSlugsRow struct {
	ID   int64  `json:"id"`
	Slug string `json:"slug"`
}

// Loaded once per slug-assignment pass (backfill or per-song on ingest)
// to answer "is this slug taken" locally rather than one query per
// candidate — the whole catalog's slugs easily fit in memory.
func (q *Queries) ListAllSongSlugs(ctx context.Context) ([]ListAllSongSlugsRow, error) {
	rows, err := q.db.Query(ctx, listAllSongSlugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllSongSlugsRow
	for rows.Next() {
		var i ListAllSongSlugsRow
		if err := rows.Scan(&i.ID, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctAddedByUsers = `-- name: ListDistinctAddedByUsers :many
SELECT DISTINCT u.name, u.email
FROM songs s
JOIN users u ON u.id = s.added_by_user_id
ORDER BY u.name
`

type ListDistinctAddedByUsersRow struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

func (q *Queries) ListDistinctAddedByUsers(ctx context.Context) ([]ListDistinctAddedByUsersRow, error) {
	rows, err := q.db.Query(ctx, listDistinctAddedByUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDistinctAddedByUsersRow
	for rows.Next() {
		var i ListDistinctAddedByUsersRow
		if err := rows.Scan(&i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctStatuses = `-- name: ListDistinctStatuses :many
SELECT DISTINCT status FROM songs WHERE status <> '' ORDER BY status
`

func (q *Queries) ListDistinctStatuses(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listDistinctStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var status string
		if err := rows.Scan(&status); err != nil {
			return nil, err
		}
		items = append(items, status)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSongIDsWithoutCurrentVersion = `-- name: ListSongIDsWithoutCurrentVersion :many
SELECT id FROM songs WHERE current_version_id IS NULL ORDER BY id ASC LIMIT $1
`

func (q *Queries) ListSongIDsWithoutCurrentVersion(ctx context.Context, limit int32) ([]int64, error) {
	rows, err := q.db.Query(ctx, listSongIDsWithoutCurrentVersion, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSongsByTitle = `-- name: ListSongsByTitle :many

SELECT songs.id, songs.title, songs.artist, songs.genre, songs.film_show_album, songs.decade, songs.bob_tag, songs.status, songs.source_url, songs.notes, songs.transpose_hint, songs.google_doc_id, songs.current_version_id, songs.added_by_user_id, songs.created_at, songs.updated_at, songs.artist_id, songs.preferred_key, songs.doc_created_at, songs.doc_modified_at, songs.source_site, songs.slug, users.name AS added_by_name, users.email AS added_by_email
FROM songs
LEFT JOIN users ON users.id = songs.added_by_user_id
ORDER BY lower(songs.title) ASC, lower(songs.artist) ASC
`

type ListSongsByTitleRow struct {
	ID               int64              `json:"id"`
	Title            string             `json:"title"`
	Artist           string             `json:"artist"`
	Genre            string             `json:"genre"`
	FilmShowAlbum    string             `json:"film_show_album"`
	Decade           string             `json:"decade"`
	BobTag           string             `json:"bob_tag"`
	Status           string             `json:"status"`
	SourceUrl        string             `json:"source_url"`
	Notes            string             `json:"notes"`
	TransposeHint    string             `json:"transpose_hint"`
	GoogleDocID      string             `json:"google_doc_id"`
	CurrentVersionID *int64             `json:"current_version_id"`
	AddedByUserID    *int64             `json:"added_by_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ArtistID         *int64             `json:"artist_id"`
	PreferredKey     string             `json:"preferred_key"`
	DocCreatedAt     pgtype.Timestamptz `json:"doc_created_at"`
	DocModifiedAt    pgtype.Timestamptz `json:"doc_modified_at"`
	SourceSite       string             `json:"source_site"`
	Slug             string             `json:"slug"`
	AddedByName      *string            `json:"added_by_name"`
	AddedByEmail     *string            `json:"added_by_email"`
}

// Every ListSongsBy* query below returns the same column set (song columns
// plus the joined added-by name/email) so the home page table always has
// every column available no matter which one is sorting it. sqlc can't
// parametrize ORDER BY, hence one near-identical query per sort column
// rather than a single dynamic one.
func (q *Queries) ListSongsByTitle(ctx context.Context) ([]ListSongsByTitleRow, error) {
	rows, err := q.db.Query(ctx, listSongsByTitle)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSongsByTitleRow
	for rows.Next() {
		var i ListSongsByTitleRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artist,
			&i.Genre,
			&i.FilmShowAlbum,
			&i.Decade,
			&i.BobTag,
			&i.Status,
			&i.SourceUrl,
			&i.Notes,
			&i.TransposeHint,
			&i.GoogleDocID,
			&i.CurrentVersionID,
			&i.AddedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArtistID,
			&i.PreferredKey,
			&i.DocCreatedAt,
			&i.DocModifiedAt,
			&i.SourceSite,
			&i.Slug,
			&i.AddedByName,
			&i.AddedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSongCurrentVersion = `-- name: SetSongCurrentVersion :exec
UPDATE songs SET current_version_id = $2, updated_at = now() WHERE id = $1
`

type SetSongCurrentVersionParams struct {
	ID               int64  `json:"id"`
	CurrentVersionID *int64 `json:"current_version_id"`
}

func (q *Queries) SetSongCurrentVersion(ctx context.Context, arg SetSongCurrentVersionParams) error {
	_, err := q.db.Exec(ctx, setSongCurrentVersion, arg.ID, arg.CurrentVersionID)
	return err
}

const setSongDocTimestamps = `-- name: SetSongDocTimestamps :exec
UPDATE songs SET doc_created_at = $2, doc_modified_at = $3 WHERE id = $1
`

type SetSongDocTimestampsParams struct {
	ID            int64              `json:"id"`
	DocCreatedAt  pgtype.Timestamptz `json:"doc_created_at"`
	DocModifiedAt pgtype.Timestamptz `json:"doc_modified_at"`
}

// Deliberately does not touch updated_at — these mirror the Google Doc's
// own createdTime/modifiedTime, not a tabitha-side content change.
func (q *Queries) SetSongDocTimestamps(ctx context.Context, arg SetSongDocTimestampsParams) error {
	_, err := q.db.Exec(ctx, setSongDocTimestamps, arg.ID, arg.DocCreatedAt, arg.DocModifiedAt)
	return err
}

const setSongGoogleDocID = `-- name: SetSongGoogleDocID :exec
UPDATE songs SET google_doc_id = $2, updated_at = now() WHERE id = $1
`

type SetSongGoogleDocIDParams struct {
	ID          int64  `json:"id"`
	GoogleDocID string `json:"google_doc_id"`
}

func (q *Queries) SetSongGoogleDocID(ctx context.Context, arg SetSongGoogleDocIDParams) error {
	_, err := q.db.Exec(ctx, setSongGoogleDocID, arg.ID, arg.GoogleDocID)
	return err
}

const setSongPreferredKey = `-- name: SetSongPreferredKey :exec
UPDATE songs SET preferred_key = $2, updated_at = now() WHERE id = $1
`

type SetSongPreferredKeyParams struct {
	ID           int64  `json:"id"`
	PreferredKey string `json:"preferred_key"`
}

func (q *Queries) SetSongPreferredKey(ctx context.Context, arg SetSongPreferredKeyParams) error {
	_, err := q.db.Exec(ctx, setSongPreferredKey, arg.ID, arg.PreferredKey)
	return err
}

const setSongSlug = `-- name: SetSongSlug :exec
UPDATE songs SET slug = $2 WHERE id = $1
`

type SetSongSlugParams struct {
	ID   int64  `json:"id"`
	Slug string `json:"slug"`
}

func (q *Queries) SetSongSlug(ctx context.Context, arg SetSongSlugParams) error {
	_, err := q.db.Exec(ctx, setSongSlug, arg.ID, arg.Slug)
	return err
}

const setSongStatus = `-- name: SetSongStatus :exec
UPDATE songs SET status = $2, updated_at = now() WHERE id = $1
`

type SetSongStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) SetSongStatus(ctx context.Context, arg SetSongStatusParams) error {
	_, err := q.db.Exec(ctx, setSongStatus, arg.ID, arg.Status)
	return err
}

const setSongsStatusBulk = `-- name: SetSongsStatusBulk :exec
UPDATE songs SET status = $2, updated_at = now() WHERE id = ANY($1::bigint[])
`

type SetSongsStatusBulkParams struct {
	Column1 []int64 `json:"column_1"`
	Status  string  `json:"status"`
}

func (q *Queries) SetSongsStatusBulk(ctx context.Context, arg SetSongsStatusBulkParams) error {
	_, err := q.db.Exec(ctx, setSongsStatusBulk, arg.Column1, arg.Status)
	return err
}

const upsertSongFromTOC = `-- name: UpsertSongFromTOC :one
INSERT INTO songs (
    title, artist, genre, film_show_album, decade, bob_tag, status,
    source_url, notes, transpose_hint
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
ON CONFLICT (lower(title), lower(artist)) DO UPDATE SET
    genre = EXCLUDED.genre,
    film_show_album = EXCLUDED.film_show_album,
    decade = EXCLUDED.decade,
    bob_tag = EXCLUDED.bob_tag,
    status = EXCLUDED.status,
    source_url = EXCLUDED.source_url,
    notes = EXCLUDED.notes,
    transpose_hint = EXCLUDED.transpose_hint,
    updated_at = now()
RETURNING id, title, artist, genre, film_show_album, decade, bob_tag, status, source_url, notes, transpose_hint, google_doc_id, current_version_id, added_by_user_id, created_at, updated_at, artist_id, preferred_key, doc_created_at, doc_modified_at, source_site, slug
`

type UpsertSongFromTOCParams struct {
	Title         string `json:"title"`
	Artist        string `json:"artist"`
	Genre         string `json:"genre"`
	FilmShowAlbum string `json:"film_show_album"`
	Decade        string `json:"decade"`
	BobTag        string `json:"bob_tag"`
	Status        string `json:"status"`
	SourceUrl     string `json:"source_url"`
	Notes         string `json:"notes"`
	TransposeHint string `json:"transpose_hint"`
}

func (q *Queries) UpsertSongFromTOC(ctx context.Context, arg UpsertSongFromTOCParams) (Song, error) {
	row := q.db.QueryRow(ctx, upsertSongFromTOC,
		arg.Title,
		arg.Artist,
		arg.Genre,
		arg.FilmShowAlbum,
		arg.Decade,
		arg.BobTag,
		arg.Status,
		arg.SourceUrl,
		arg.Notes,
		arg.TransposeHint,
	)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Artist,
		&i.Genre,
		&i.FilmShowAlbum,
		&i.Decade,
		&i.BobTag,
		&i.Status,
		&i.SourceUrl,
		&i.Notes,
		&i.TransposeHint,
		&i.GoogleDocID,
		&i.CurrentVersionID,
		&i.AddedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArtistID,
		&i.PreferredKey,
		&i.DocCreatedAt,
		&i.DocModifiedAt,
		&i.SourceSite,
		&i.Slug,
	)
	return i, err
}
