// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: songs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSongByID = `-- name: GetSongByID :one
SELECT id, title, artist, genre, film_show_album, decade, bob_tag, status, source_url, notes, transpose_hint, google_doc_id, current_version_id, added_by_user_id, created_at, updated_at FROM songs WHERE id = $1
`

func (q *Queries) GetSongByID(ctx context.Context, id int64) (Song, error) {
	row := q.db.QueryRow(ctx, getSongByID, id)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Artist,
		&i.Genre,
		&i.FilmShowAlbum,
		&i.Decade,
		&i.BobTag,
		&i.Status,
		&i.SourceUrl,
		&i.Notes,
		&i.TransposeHint,
		&i.GoogleDocID,
		&i.CurrentVersionID,
		&i.AddedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSongCurrentVersion = `-- name: GetSongCurrentVersion :one
SELECT songs.id, songs.title, songs.artist, songs.genre, songs.film_show_album, songs.decade, songs.bob_tag, songs.status, songs.source_url, songs.notes, songs.transpose_hint, songs.google_doc_id, songs.current_version_id, songs.added_by_user_id, songs.created_at, songs.updated_at, transcription_versions.id, transcription_versions.song_id, transcription_versions.kind, transcription_versions.source, transcription_versions.raw_text, transcription_versions.content, transcription_versions.key, transcription_versions.capo, transcription_versions.is_current, transcription_versions.created_by, transcription_versions.created_at
FROM songs
JOIN transcription_versions ON transcription_versions.id = songs.current_version_id
WHERE songs.id = $1
`

type GetSongCurrentVersionRow struct {
	Song                 Song                 `json:"song"`
	TranscriptionVersion TranscriptionVersion `json:"transcription_version"`
}

func (q *Queries) GetSongCurrentVersion(ctx context.Context, id int64) (GetSongCurrentVersionRow, error) {
	row := q.db.QueryRow(ctx, getSongCurrentVersion, id)
	var i GetSongCurrentVersionRow
	err := row.Scan(
		&i.Song.ID,
		&i.Song.Title,
		&i.Song.Artist,
		&i.Song.Genre,
		&i.Song.FilmShowAlbum,
		&i.Song.Decade,
		&i.Song.BobTag,
		&i.Song.Status,
		&i.Song.SourceUrl,
		&i.Song.Notes,
		&i.Song.TransposeHint,
		&i.Song.GoogleDocID,
		&i.Song.CurrentVersionID,
		&i.Song.AddedByUserID,
		&i.Song.CreatedAt,
		&i.Song.UpdatedAt,
		&i.TranscriptionVersion.ID,
		&i.TranscriptionVersion.SongID,
		&i.TranscriptionVersion.Kind,
		&i.TranscriptionVersion.Source,
		&i.TranscriptionVersion.RawText,
		&i.TranscriptionVersion.Content,
		&i.TranscriptionVersion.Key,
		&i.TranscriptionVersion.Capo,
		&i.TranscriptionVersion.IsCurrent,
		&i.TranscriptionVersion.CreatedBy,
		&i.TranscriptionVersion.CreatedAt,
	)
	return i, err
}

const listSongsByAddedBy = `-- name: ListSongsByAddedBy :many
SELECT songs.id, songs.title, songs.artist, songs.genre, songs.film_show_album, songs.decade, songs.bob_tag, songs.status, songs.source_url, songs.notes, songs.transpose_hint, songs.google_doc_id, songs.current_version_id, songs.added_by_user_id, songs.created_at, songs.updated_at, users.name AS added_by_name, users.email AS added_by_email
FROM songs
LEFT JOIN users ON users.id = songs.added_by_user_id
ORDER BY lower(users.email) ASC NULLS LAST, lower(songs.title) ASC
`

type ListSongsByAddedByRow struct {
	ID               int64              `json:"id"`
	Title            string             `json:"title"`
	Artist           string             `json:"artist"`
	Genre            string             `json:"genre"`
	FilmShowAlbum    string             `json:"film_show_album"`
	Decade           string             `json:"decade"`
	BobTag           string             `json:"bob_tag"`
	Status           string             `json:"status"`
	SourceUrl        string             `json:"source_url"`
	Notes            string             `json:"notes"`
	TransposeHint    string             `json:"transpose_hint"`
	GoogleDocID      string             `json:"google_doc_id"`
	CurrentVersionID *int64             `json:"current_version_id"`
	AddedByUserID    *int64             `json:"added_by_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	AddedByName      *string            `json:"added_by_name"`
	AddedByEmail     *string            `json:"added_by_email"`
}

func (q *Queries) ListSongsByAddedBy(ctx context.Context) ([]ListSongsByAddedByRow, error) {
	rows, err := q.db.Query(ctx, listSongsByAddedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSongsByAddedByRow
	for rows.Next() {
		var i ListSongsByAddedByRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artist,
			&i.Genre,
			&i.FilmShowAlbum,
			&i.Decade,
			&i.BobTag,
			&i.Status,
			&i.SourceUrl,
			&i.Notes,
			&i.TransposeHint,
			&i.GoogleDocID,
			&i.CurrentVersionID,
			&i.AddedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AddedByName,
			&i.AddedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSongsByArtist = `-- name: ListSongsByArtist :many
SELECT songs.id, songs.title, songs.artist, songs.genre, songs.film_show_album, songs.decade, songs.bob_tag, songs.status, songs.source_url, songs.notes, songs.transpose_hint, songs.google_doc_id, songs.current_version_id, songs.added_by_user_id, songs.created_at, songs.updated_at, users.name AS added_by_name, users.email AS added_by_email
FROM songs
LEFT JOIN users ON users.id = songs.added_by_user_id
ORDER BY lower(songs.artist) ASC, lower(songs.title) ASC
`

type ListSongsByArtistRow struct {
	ID               int64              `json:"id"`
	Title            string             `json:"title"`
	Artist           string             `json:"artist"`
	Genre            string             `json:"genre"`
	FilmShowAlbum    string             `json:"film_show_album"`
	Decade           string             `json:"decade"`
	BobTag           string             `json:"bob_tag"`
	Status           string             `json:"status"`
	SourceUrl        string             `json:"source_url"`
	Notes            string             `json:"notes"`
	TransposeHint    string             `json:"transpose_hint"`
	GoogleDocID      string             `json:"google_doc_id"`
	CurrentVersionID *int64             `json:"current_version_id"`
	AddedByUserID    *int64             `json:"added_by_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	AddedByName      *string            `json:"added_by_name"`
	AddedByEmail     *string            `json:"added_by_email"`
}

func (q *Queries) ListSongsByArtist(ctx context.Context) ([]ListSongsByArtistRow, error) {
	rows, err := q.db.Query(ctx, listSongsByArtist)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSongsByArtistRow
	for rows.Next() {
		var i ListSongsByArtistRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artist,
			&i.Genre,
			&i.FilmShowAlbum,
			&i.Decade,
			&i.BobTag,
			&i.Status,
			&i.SourceUrl,
			&i.Notes,
			&i.TransposeHint,
			&i.GoogleDocID,
			&i.CurrentVersionID,
			&i.AddedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AddedByName,
			&i.AddedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSongsByLastUpdated = `-- name: ListSongsByLastUpdated :many
SELECT songs.id, songs.title, songs.artist, songs.genre, songs.film_show_album, songs.decade, songs.bob_tag, songs.status, songs.source_url, songs.notes, songs.transpose_hint, songs.google_doc_id, songs.current_version_id, songs.added_by_user_id, songs.created_at, songs.updated_at, users.name AS added_by_name, users.email AS added_by_email
FROM songs
LEFT JOIN users ON users.id = songs.added_by_user_id
ORDER BY songs.updated_at DESC
`

type ListSongsByLastUpdatedRow struct {
	ID               int64              `json:"id"`
	Title            string             `json:"title"`
	Artist           string             `json:"artist"`
	Genre            string             `json:"genre"`
	FilmShowAlbum    string             `json:"film_show_album"`
	Decade           string             `json:"decade"`
	BobTag           string             `json:"bob_tag"`
	Status           string             `json:"status"`
	SourceUrl        string             `json:"source_url"`
	Notes            string             `json:"notes"`
	TransposeHint    string             `json:"transpose_hint"`
	GoogleDocID      string             `json:"google_doc_id"`
	CurrentVersionID *int64             `json:"current_version_id"`
	AddedByUserID    *int64             `json:"added_by_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	AddedByName      *string            `json:"added_by_name"`
	AddedByEmail     *string            `json:"added_by_email"`
}

func (q *Queries) ListSongsByLastUpdated(ctx context.Context) ([]ListSongsByLastUpdatedRow, error) {
	rows, err := q.db.Query(ctx, listSongsByLastUpdated)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSongsByLastUpdatedRow
	for rows.Next() {
		var i ListSongsByLastUpdatedRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artist,
			&i.Genre,
			&i.FilmShowAlbum,
			&i.Decade,
			&i.BobTag,
			&i.Status,
			&i.SourceUrl,
			&i.Notes,
			&i.TransposeHint,
			&i.GoogleDocID,
			&i.CurrentVersionID,
			&i.AddedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AddedByName,
			&i.AddedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSongsByRecentlyAdded = `-- name: ListSongsByRecentlyAdded :many
SELECT songs.id, songs.title, songs.artist, songs.genre, songs.film_show_album, songs.decade, songs.bob_tag, songs.status, songs.source_url, songs.notes, songs.transpose_hint, songs.google_doc_id, songs.current_version_id, songs.added_by_user_id, songs.created_at, songs.updated_at, users.name AS added_by_name, users.email AS added_by_email
FROM songs
LEFT JOIN users ON users.id = songs.added_by_user_id
ORDER BY songs.created_at DESC
`

type ListSongsByRecentlyAddedRow struct {
	ID               int64              `json:"id"`
	Title            string             `json:"title"`
	Artist           string             `json:"artist"`
	Genre            string             `json:"genre"`
	FilmShowAlbum    string             `json:"film_show_album"`
	Decade           string             `json:"decade"`
	BobTag           string             `json:"bob_tag"`
	Status           string             `json:"status"`
	SourceUrl        string             `json:"source_url"`
	Notes            string             `json:"notes"`
	TransposeHint    string             `json:"transpose_hint"`
	GoogleDocID      string             `json:"google_doc_id"`
	CurrentVersionID *int64             `json:"current_version_id"`
	AddedByUserID    *int64             `json:"added_by_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	AddedByName      *string            `json:"added_by_name"`
	AddedByEmail     *string            `json:"added_by_email"`
}

func (q *Queries) ListSongsByRecentlyAdded(ctx context.Context) ([]ListSongsByRecentlyAddedRow, error) {
	rows, err := q.db.Query(ctx, listSongsByRecentlyAdded)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSongsByRecentlyAddedRow
	for rows.Next() {
		var i ListSongsByRecentlyAddedRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artist,
			&i.Genre,
			&i.FilmShowAlbum,
			&i.Decade,
			&i.BobTag,
			&i.Status,
			&i.SourceUrl,
			&i.Notes,
			&i.TransposeHint,
			&i.GoogleDocID,
			&i.CurrentVersionID,
			&i.AddedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AddedByName,
			&i.AddedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSongsByStatus = `-- name: ListSongsByStatus :many
SELECT songs.id, songs.title, songs.artist, songs.genre, songs.film_show_album, songs.decade, songs.bob_tag, songs.status, songs.source_url, songs.notes, songs.transpose_hint, songs.google_doc_id, songs.current_version_id, songs.added_by_user_id, songs.created_at, songs.updated_at, users.name AS added_by_name, users.email AS added_by_email
FROM songs
LEFT JOIN users ON users.id = songs.added_by_user_id
ORDER BY lower(songs.status) ASC, lower(songs.title) ASC
`

type ListSongsByStatusRow struct {
	ID               int64              `json:"id"`
	Title            string             `json:"title"`
	Artist           string             `json:"artist"`
	Genre            string             `json:"genre"`
	FilmShowAlbum    string             `json:"film_show_album"`
	Decade           string             `json:"decade"`
	BobTag           string             `json:"bob_tag"`
	Status           string             `json:"status"`
	SourceUrl        string             `json:"source_url"`
	Notes            string             `json:"notes"`
	TransposeHint    string             `json:"transpose_hint"`
	GoogleDocID      string             `json:"google_doc_id"`
	CurrentVersionID *int64             `json:"current_version_id"`
	AddedByUserID    *int64             `json:"added_by_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	AddedByName      *string            `json:"added_by_name"`
	AddedByEmail     *string            `json:"added_by_email"`
}

func (q *Queries) ListSongsByStatus(ctx context.Context) ([]ListSongsByStatusRow, error) {
	rows, err := q.db.Query(ctx, listSongsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSongsByStatusRow
	for rows.Next() {
		var i ListSongsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artist,
			&i.Genre,
			&i.FilmShowAlbum,
			&i.Decade,
			&i.BobTag,
			&i.Status,
			&i.SourceUrl,
			&i.Notes,
			&i.TransposeHint,
			&i.GoogleDocID,
			&i.CurrentVersionID,
			&i.AddedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AddedByName,
			&i.AddedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSongsByTitle = `-- name: ListSongsByTitle :many

SELECT songs.id, songs.title, songs.artist, songs.genre, songs.film_show_album, songs.decade, songs.bob_tag, songs.status, songs.source_url, songs.notes, songs.transpose_hint, songs.google_doc_id, songs.current_version_id, songs.added_by_user_id, songs.created_at, songs.updated_at, users.name AS added_by_name, users.email AS added_by_email
FROM songs
LEFT JOIN users ON users.id = songs.added_by_user_id
ORDER BY lower(songs.title) ASC, lower(songs.artist) ASC
`

type ListSongsByTitleRow struct {
	ID               int64              `json:"id"`
	Title            string             `json:"title"`
	Artist           string             `json:"artist"`
	Genre            string             `json:"genre"`
	FilmShowAlbum    string             `json:"film_show_album"`
	Decade           string             `json:"decade"`
	BobTag           string             `json:"bob_tag"`
	Status           string             `json:"status"`
	SourceUrl        string             `json:"source_url"`
	Notes            string             `json:"notes"`
	TransposeHint    string             `json:"transpose_hint"`
	GoogleDocID      string             `json:"google_doc_id"`
	CurrentVersionID *int64             `json:"current_version_id"`
	AddedByUserID    *int64             `json:"added_by_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	AddedByName      *string            `json:"added_by_name"`
	AddedByEmail     *string            `json:"added_by_email"`
}

// Every ListSongsBy* query below returns the same column set (song columns
// plus the joined added-by name/email) so the home page table always has
// every column available no matter which one is sorting it. sqlc can't
// parametrize ORDER BY, hence one near-identical query per sort column
// rather than a single dynamic one.
func (q *Queries) ListSongsByTitle(ctx context.Context) ([]ListSongsByTitleRow, error) {
	rows, err := q.db.Query(ctx, listSongsByTitle)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSongsByTitleRow
	for rows.Next() {
		var i ListSongsByTitleRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artist,
			&i.Genre,
			&i.FilmShowAlbum,
			&i.Decade,
			&i.BobTag,
			&i.Status,
			&i.SourceUrl,
			&i.Notes,
			&i.TransposeHint,
			&i.GoogleDocID,
			&i.CurrentVersionID,
			&i.AddedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AddedByName,
			&i.AddedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSongCurrentVersion = `-- name: SetSongCurrentVersion :exec
UPDATE songs SET current_version_id = $2, updated_at = now() WHERE id = $1
`

type SetSongCurrentVersionParams struct {
	ID               int64  `json:"id"`
	CurrentVersionID *int64 `json:"current_version_id"`
}

func (q *Queries) SetSongCurrentVersion(ctx context.Context, arg SetSongCurrentVersionParams) error {
	_, err := q.db.Exec(ctx, setSongCurrentVersion, arg.ID, arg.CurrentVersionID)
	return err
}

const setSongGoogleDocID = `-- name: SetSongGoogleDocID :exec
UPDATE songs SET google_doc_id = $2, updated_at = now() WHERE id = $1
`

type SetSongGoogleDocIDParams struct {
	ID          int64  `json:"id"`
	GoogleDocID string `json:"google_doc_id"`
}

func (q *Queries) SetSongGoogleDocID(ctx context.Context, arg SetSongGoogleDocIDParams) error {
	_, err := q.db.Exec(ctx, setSongGoogleDocID, arg.ID, arg.GoogleDocID)
	return err
}

const upsertSongFromTOC = `-- name: UpsertSongFromTOC :one
INSERT INTO songs (
    title, artist, genre, film_show_album, decade, bob_tag, status,
    source_url, notes, transpose_hint
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
ON CONFLICT (lower(title), lower(artist)) DO UPDATE SET
    genre = EXCLUDED.genre,
    film_show_album = EXCLUDED.film_show_album,
    decade = EXCLUDED.decade,
    bob_tag = EXCLUDED.bob_tag,
    status = EXCLUDED.status,
    source_url = EXCLUDED.source_url,
    notes = EXCLUDED.notes,
    transpose_hint = EXCLUDED.transpose_hint,
    updated_at = now()
RETURNING id, title, artist, genre, film_show_album, decade, bob_tag, status, source_url, notes, transpose_hint, google_doc_id, current_version_id, added_by_user_id, created_at, updated_at
`

type UpsertSongFromTOCParams struct {
	Title         string `json:"title"`
	Artist        string `json:"artist"`
	Genre         string `json:"genre"`
	FilmShowAlbum string `json:"film_show_album"`
	Decade        string `json:"decade"`
	BobTag        string `json:"bob_tag"`
	Status        string `json:"status"`
	SourceUrl     string `json:"source_url"`
	Notes         string `json:"notes"`
	TransposeHint string `json:"transpose_hint"`
}

func (q *Queries) UpsertSongFromTOC(ctx context.Context, arg UpsertSongFromTOCParams) (Song, error) {
	row := q.db.QueryRow(ctx, upsertSongFromTOC,
		arg.Title,
		arg.Artist,
		arg.Genre,
		arg.FilmShowAlbum,
		arg.Decade,
		arg.BobTag,
		arg.Status,
		arg.SourceUrl,
		arg.Notes,
		arg.TransposeHint,
	)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Artist,
		&i.Genre,
		&i.FilmShowAlbum,
		&i.Decade,
		&i.BobTag,
		&i.Status,
		&i.SourceUrl,
		&i.Notes,
		&i.TransposeHint,
		&i.GoogleDocID,
		&i.CurrentVersionID,
		&i.AddedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
