// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGoogleOAuthTokenByUserID = `-- name: GetGoogleOAuthTokenByUserID :one
SELECT id, user_id, encrypted_access_token, encrypted_refresh_token, scope, expiry, created_at, updated_at FROM google_oauth_tokens WHERE user_id = $1
`

func (q *Queries) GetGoogleOAuthTokenByUserID(ctx context.Context, userID int64) (GoogleOauthToken, error) {
	row := q.db.QueryRow(ctx, getGoogleOAuthTokenByUserID, userID)
	var i GoogleOauthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EncryptedAccessToken,
		&i.EncryptedRefreshToken,
		&i.Scope,
		&i.Expiry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGoogleOAuthToken = `-- name: UpsertGoogleOAuthToken :exec
INSERT INTO google_oauth_tokens (
    user_id, encrypted_access_token, encrypted_refresh_token, scope, expiry
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (user_id) DO UPDATE SET
    encrypted_access_token = EXCLUDED.encrypted_access_token,
    encrypted_refresh_token = EXCLUDED.encrypted_refresh_token,
    scope = EXCLUDED.scope,
    expiry = EXCLUDED.expiry,
    updated_at = now()
`

type UpsertGoogleOAuthTokenParams struct {
	UserID                int64              `json:"user_id"`
	EncryptedAccessToken  []byte             `json:"encrypted_access_token"`
	EncryptedRefreshToken []byte             `json:"encrypted_refresh_token"`
	Scope                 string             `json:"scope"`
	Expiry                pgtype.Timestamptz `json:"expiry"`
}

func (q *Queries) UpsertGoogleOAuthToken(ctx context.Context, arg UpsertGoogleOAuthTokenParams) error {
	_, err := q.db.Exec(ctx, upsertGoogleOAuthToken,
		arg.UserID,
		arg.EncryptedAccessToken,
		arg.EncryptedRefreshToken,
		arg.Scope,
		arg.Expiry,
	)
	return err
}
