// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: versions.sql

package db

import (
	"context"
)

const clearCurrentVersionsForSong = `-- name: ClearCurrentVersionsForSong :exec
UPDATE transcription_versions SET is_current = false WHERE song_id = $1 AND is_current
`

func (q *Queries) ClearCurrentVersionsForSong(ctx context.Context, songID int64) error {
	_, err := q.db.Exec(ctx, clearCurrentVersionsForSong, songID)
	return err
}

const createTranscriptionVersion = `-- name: CreateTranscriptionVersion :one
INSERT INTO transcription_versions (
    song_id, kind, source, raw_text, content, key, capo, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, song_id, kind, source, raw_text, content, key, capo, is_current, created_by, created_at
`

type CreateTranscriptionVersionParams struct {
	SongID    int64   `json:"song_id"`
	Kind      string  `json:"kind"`
	Source    string  `json:"source"`
	RawText   string  `json:"raw_text"`
	Content   []byte  `json:"content"`
	Key       *string `json:"key"`
	Capo      *int32  `json:"capo"`
	CreatedBy *int64  `json:"created_by"`
}

func (q *Queries) CreateTranscriptionVersion(ctx context.Context, arg CreateTranscriptionVersionParams) (TranscriptionVersion, error) {
	row := q.db.QueryRow(ctx, createTranscriptionVersion,
		arg.SongID,
		arg.Kind,
		arg.Source,
		arg.RawText,
		arg.Content,
		arg.Key,
		arg.Capo,
		arg.CreatedBy,
	)
	var i TranscriptionVersion
	err := row.Scan(
		&i.ID,
		&i.SongID,
		&i.Kind,
		&i.Source,
		&i.RawText,
		&i.Content,
		&i.Key,
		&i.Capo,
		&i.IsCurrent,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getTranscriptionVersion = `-- name: GetTranscriptionVersion :one
SELECT id, song_id, kind, source, raw_text, content, key, capo, is_current, created_by, created_at FROM transcription_versions WHERE id = $1
`

func (q *Queries) GetTranscriptionVersion(ctx context.Context, id int64) (TranscriptionVersion, error) {
	row := q.db.QueryRow(ctx, getTranscriptionVersion, id)
	var i TranscriptionVersion
	err := row.Scan(
		&i.ID,
		&i.SongID,
		&i.Kind,
		&i.Source,
		&i.RawText,
		&i.Content,
		&i.Key,
		&i.Capo,
		&i.IsCurrent,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listAllCurrentVersionIDsAndRawText = `-- name: ListAllCurrentVersionIDsAndRawText :many
SELECT tv.id, tv.raw_text
FROM transcription_versions tv
JOIN songs s ON s.current_version_id = tv.id
`

type ListAllCurrentVersionIDsAndRawTextRow struct {
	ID      int64  `json:"id"`
	RawText string `json:"raw_text"`
}

func (q *Queries) ListAllCurrentVersionIDsAndRawText(ctx context.Context) ([]ListAllCurrentVersionIDsAndRawTextRow, error) {
	rows, err := q.db.Query(ctx, listAllCurrentVersionIDsAndRawText)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllCurrentVersionIDsAndRawTextRow
	for rows.Next() {
		var i ListAllCurrentVersionIDsAndRawTextRow
		if err := rows.Scan(&i.ID, &i.RawText); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersionsForSong = `-- name: ListVersionsForSong :many
SELECT id, song_id, kind, source, raw_text, content, key, capo, is_current, created_by, created_at FROM transcription_versions WHERE song_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListVersionsForSong(ctx context.Context, songID int64) ([]TranscriptionVersion, error) {
	rows, err := q.db.Query(ctx, listVersionsForSong, songID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TranscriptionVersion
	for rows.Next() {
		var i TranscriptionVersion
		if err := rows.Scan(
			&i.ID,
			&i.SongID,
			&i.Kind,
			&i.Source,
			&i.RawText,
			&i.Content,
			&i.Key,
			&i.Capo,
			&i.IsCurrent,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markVersionCurrent = `-- name: MarkVersionCurrent :exec
UPDATE transcription_versions SET is_current = true WHERE id = $1
`

func (q *Queries) MarkVersionCurrent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markVersionCurrent, id)
	return err
}

const updateTranscriptionVersionContent = `-- name: UpdateTranscriptionVersionContent :exec
UPDATE transcription_versions SET content = $2 WHERE id = $1
`

type UpdateTranscriptionVersionContentParams struct {
	ID      int64  `json:"id"`
	Content []byte `json:"content"`
}

// Re-derives content from the already-stored raw_text after a parser
// classification improvement — no re-fetch from Google needed since
// raw_text itself doesn't change, only how it's parsed into blocks.
func (q *Queries) UpdateTranscriptionVersionContent(ctx context.Context, arg UpdateTranscriptionVersionContentParams) error {
	_, err := q.db.Exec(ctx, updateTranscriptionVersionContent, arg.ID, arg.Content)
	return err
}
